[versions]
kotlin = "2.3.10"
http4k = "6.46.0.0"
shadow = "9.3.0"
junit = "6.0.3"

[libraries]
http4k-bom = { module = "org.http4k:http4k-bom", version.ref = "http4k" }
http4k-ai-sdk = { module = "org.http4k.pro:http4k-ai-a2a-sdk" }
http4k-ai-client = { module = "org.http4k.pro:http4k-ai-a2a-client" }
http4k-config = { module = "org.http4k:http4k-config" }
http4k-core = { module = "org.http4k:http4k-core" }
http4k-format-moshi = { module = "org.http4k:http4k-format-moshi" }
http4k-server-jetty = { module = "org.http4k:http4k-server-jetty" }
http4k-testing-hamkrest = { module = "org.http4k:http4k-testing-hamkrest" }
http4k-testing-kotest = { module = "org.http4k:http4k-testing-kotest" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
